spring.application.name=seohelper

spring.datasource.url=jdbc:postgresql://localhost:5432/seohelper_db
spring.datasource.username=user
spring.datasource.password=user

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

google.pagespeed.api.key = AIzaSyAZdIwwv4bV9syFHFlbtqmCuoMayznIjCM
ollama.api.key=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
ollama.api.url=http://localhost:11434/api/generate
spring.redis.host=localhost
spring.redis.password=user
spring.redis.port = 6380
spring.redis.timeout=5000
spring.cache.type=redis
