spring.application.name=seohelper

spring.datasource.url=jdbc:postgresql://localhost:5432/seohelper_db
spring.datasource.username=user
spring.datasource.password=user

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
